package life.majiang.common.community.mapper;

import java.util.List;
import life.majiang.common.community.model.Question1;
import life.majiang.common.community.model.Question1Example;
import org.apache.ibatis.annotations.Param;

public interface Question1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Apr 22 12:30:18 CST 2020
     */
    long countByExample(Question1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Apr 22 12:30:18 CST 2020
     */
    int deleteByExample(Question1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Apr 22 12:30:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Apr 22 12:30:18 CST 2020
     */
    int insert(Question1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Apr 22 12:30:18 CST 2020
     */
    int insertSelective(Question1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Apr 22 12:30:18 CST 2020
     */
    List<Question1> selectByExampleWithBLOBs(Question1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Apr 22 12:30:18 CST 2020
     */
    List<Question1> selectByExample(Question1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Apr 22 12:30:18 CST 2020
     */
    Question1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Apr 22 12:30:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Question1 record, @Param("example") Question1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Apr 22 12:30:18 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Question1 record, @Param("example") Question1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Apr 22 12:30:18 CST 2020
     */
    int updateByExample(@Param("record") Question1 record, @Param("example") Question1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Apr 22 12:30:18 CST 2020
     */
    int updateByPrimaryKeySelective(Question1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Apr 22 12:30:18 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Question1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Apr 22 12:30:18 CST 2020
     */
    int updateByPrimaryKey(Question1 record);
}