package life.majiang.common.community.mapper;

import java.util.List;
import life.majiang.common.community.model.User1;
import life.majiang.common.community.model.User1Example;
import org.apache.ibatis.annotations.Param;

public interface User1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 22 10:54:30 CST 2020
     */
    long countByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 22 10:54:30 CST 2020
     */
    int deleteByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 22 10:54:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 22 10:54:30 CST 2020
     */
    int insert(User1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 22 10:54:30 CST 2020
     */
    int insertSelective(User1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 22 10:54:30 CST 2020
     */
    List<User1> selectByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 22 10:54:30 CST 2020
     */
    User1 selectByPrimaryKey(Integer id);
    User1 selectByPrimaryAccountId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 22 10:54:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") User1 record, @Param("example") User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 22 10:54:30 CST 2020
     */
    int updateByExample(@Param("record") User1 record, @Param("example") User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 22 10:54:30 CST 2020
     */
    int updateByPrimaryKeySelective(User1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 22 10:54:30 CST 2020
     */
    int updateByPrimaryKey(User1 record);
}